---
title: "IstantEva Deutsch"
output: github_document
bibliography: instant-eva.bib
---

## Beschreibung

* **InstantEva Deutsch** steht für *Tafelfertige Evaluation auf Deutsch*
* Instant**Eva** Deutsch ist eine interaktive online Anwendung für studentische Kursevaluationen.
* **Instant**Eva Deutsch ist wie Fertignudeln: schnell, einfach und alles in einem (Umfrage, Analyse und Zusammenfassung).
* InstantEva **Deutsch** ist im Moment nur auf Deutsch verfügbar.

Eine Demoversion von InstantEva Deutsch gibt's <a href='https://danieljach.shinyapps.io/instant-eva-deutsch/' target='_blank'>hier</a>.

Ein Beispiel für eine Zusammenfassung ist <a href='https://github.com/daniel-jach/instant-eva-deutsch/blob/master/summary.pdf' target='_blank'>hier</a> einsehbar.

Die Anwendung ist in *R* [@RCT.2013] geschrieben und nutzt *shiny* [@Chang.2020].

## Anwendung

Um die **Demoversion** von InstantEva Deutsch zu installieren, führen Sie folgende Schritte aus: 

1. Clonen Sie das Repository auf Ihren Computer. 
2. Führen Sie die Skript-Datei *setupSQLite.R* aus.
3. Laden Sie *app.R*, *evasdatabase.db* und *summary.Rmd* auf <a href='https://www.shinyapps.io/' target='_blank'>shinyapps.io</a> hoch. 

Für eine **Vollversion** von InstantEva Deutsch benötigen Sie eine Remote-MySQL-Datenbank. Anschließend führen Sie folgende Schritte aus:

1. Clonen Sie das Repository auf Ihren Computer. 
2. Führen Sie die Skript-Datei *setupMySQL.R* aus.
3. Lesen Sie durch die Skript-Datei *app.R*. Kommentieren Sie alle Code-Chunks für die Nutzung von SQLite-Datenbanken aus und aktivieren Sie stattdessen alle Code-Chunks für die Nutzung von MySQL-Datenbanken.
4. Tragen Sie die Anmeldedaten zu Ihrer Datenbank in *app.R* und *summary.Rmd* ein.
5. Laden Sie *app.R* und *summary.Rmd* auf <a href='https://www.shinyapps.io/' target='_blank'>shinyapps.io</a> hoch. 

## GFL-Dateien

Die *GFL*-Dateien enthalten einen anderen Fragebogen mit Fragen für Fremdsprachenkurse. Um diesen Fragebogen zu nutzen, führen Sie die Installationsschritte mit den *GFL*-Dateien aus.

Ein Beispiel für das Ergebnis ist <a href='https://github.com/daniel-jach/instant-eva-deutsch/blob/master/summary-GFL.pdf' target='_blank'>hier</a> einsehbar.


## Description

* **InstantEva Deutsch** stands for *Instant Evaluation in German*.
* Instant**Eva** Deutsch is an interactive online application for student course evaluations. 
* **Instant**Eva Deutsch is like instant noodles: quick, easy, and all-in-one (survey, analysis, and summary). 
* InstantEva **Deutsch** is currently only available in German. 

A demo version of InstantEva Deutsch is available <a href='https://danieljach.shinyapps.io/instant-eva-deutsch/' target='_blank'>here</a>.

An example of the summary is available <a href='https://github.com/daniel-jach/instant-eva-deutsch/blob/master/summary.pdf' target='_blank'>here</a>.

The application is written in *R* [@RCT.2013] and uses *shiny* [@Chang.2020].

## Usage

For the **demo version** of InstantEva Deutsch, do the following: 

1. Clone the repository to your local machine. 
2. Run the script file *setupSQLite.R*.
3. Upload the files *app.R*, *evasdatabase.db*, and *summary.Rmd* to <a href='https://www.shinyapps.io/' target='_blank'>shinyapps.io</a>.

For the **full version** of InstantEva Deutsch, a remote MySQL database is needed. Then, do the following: 

1. Clone the repository to your local machine. 
2. Run the script file *setupMySQL.R*.
3. Go through the *app.R* script file. Comment out the code chunks that are for use with SQLite databases and uncomment the code chunks that are for use with MySQL databases.
4. Specify the credentials of your remote MySQL database in the files *app.R* and *summary.Rmd*.
5. Upload the files *app.R* and *summary.Rmd* to <a href='https://www.shinyapps.io/' target='_blank'>shinyapps.io</a>.

## GFL files

The *GFL* files contain another questionnaire with questions adapted to the use in German as a foreign language classrooms. To use this version, run through the setup with the *GFL* files instead.

An example of the output is available <a href='https://github.com/daniel-jach/instant-eva-deutsch/blob/master/summary-GFL.pdf' target='_blank'>here</a>.

## Author  

Daniel Jach <danieljach\@protonmail.com>

## License and Copyright  

&copy; Daniel Jach, Southwest Jiaotong University, Chengdu, China

Licensed under the [MIT License](LICENSE).

## References  
